import test from 'node:test';import assert from 'node:assert/strict';import {createSpeechService} from '../src/features/speech/speech-service.js';import {renderVocabularyCard,renderVocabularySection} from '../src/components/vocabulary/vocabulary-section.js';import {contentLoader} from '../src/content/repository/content-loader.js';
function mockSpeech(voiceList=[{name:'English',lang:'en-US',voiceURI:'en-us'}]){const utterances=[];return{utterances,cancelCount:0,voices:voiceList,getVoices(){return this.voices;},speak(utterance){utterances.push(utterance);},cancel(){this.cancelCount++;}};}
class MockUtterance{constructor(text){this.text=text;this.rate=1;}}
const nextTick=()=>new Promise(resolve=>setImmediate(resolve));
test('A2, B1, and B1+ vocabulary comes from normalized unit data with dynamic counts',async()=>{for(const bookId of ['a2-foundation','b1-core','b1-plus-bridge']){const unit=await contentLoader.getUnit(`${bookId}:unit:1`);assert.equal(unit.vocabulary.length,15);const html=renderVocabularySection(unit.vocabulary);assert.match(html,new RegExp(`${unit.vocabulary.length} vocabulary items`));assert.match(html, new RegExp(unit.vocabulary[0].word.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));}});
test('Vocabulary card renders source word, part of speech, meaning, and example escaped',()=>{const item={id:'x',word:'routine',partOfSpeech:'noun',meaningInContext:'a <daily> pattern',example:'She follows a routine.'};const html=renderVocabularyCard(item);for(const text of ['routine','noun','a &lt;daily&gt; pattern','She follows a routine.'])assert.ok(html.includes(text));});
test('single item TTS reads only the requested text and chooses an English voice',async()=>{const synthesis=mockSpeech();const service=createSpeechService({synthesis,Utterance:MockUtterance});const done=service.speak('routine',{cardId:'x',kind:'word'});await nextTick();assert.equal(synthesis.utterances.length,1);assert.equal(synthesis.utterances[0].text,'routine');assert.equal(synthesis.utterances[0].lang,'en-US');assert.equal(synthesis.utterances[0].voice.voiceURI,'en-us');synthesis.utterances[0].onend();assert.equal(await done,true);});
test('Play All queues word, meaning, and example sequentially without overlap',async()=>{const synthesis=mockSpeech();const service=createSpeechService({synthesis,Utterance:MockUtterance});const done=service.playAll([{kind:'word',text:'routine'},{kind:'meaning',text:'a set of actions'},{kind:'example',text:'I have a routine.'}],{cardId:'x'});await nextTick();assert.equal(synthesis.utterances.length,1);for(let i=0;i<3;i++){const utterance=synthesis.utterances[i];utterance.onstart();utterance.onend();await nextTick();assert.equal(synthesis.utterances.length,Math.min(i+2,3));}assert.equal(await done,true);assert.deepEqual(synthesis.utterances.map(x=>x.text),['routine','a set of actions','I have a routine.']);});
test('new speech cancels prior request; stop cancels the active item',async()=>{const synthesis=mockSpeech();const service=createSpeechService({synthesis,Utterance:MockUtterance});const first=service.speak('first',{cardId:'one',kind:'word'});await nextTick();const second=service.speak('second',{cardId:'two',kind:'word'});await nextTick();assert.equal(await first,false);assert.ok(synthesis.cancelCount>=2);service.cancel();assert.equal(await second,false);});
test('rate is independent and constrained; unsupported speech fails gracefully',async()=>{const service=createSpeechService({synthesis:mockSpeech(),Utterance:MockUtterance});assert.equal(service.setRate(.8),true);assert.equal(service.setRate(2),false);const unsupported=createSpeechService({synthesis:null,Utterance:null});assert.equal(unsupported.isAvailable(),false);assert.equal(await unsupported.speak('word',{kind:'word'}),false);});
test('stopping Play All between utterances publishes cancellation and prevents the next item',async()=>{const synthesis=mockSpeech();const states=[];const service=createSpeechService({synthesis,Utterance:MockUtterance,onState:event=>states.push(event)});const done=service.playAll([{kind:'word',text:'one'},{kind:'meaning',text:'two'}],{cardId:'card'});await nextTick();synthesis.utterances[0].onend();service.cancel();assert.equal(await done,false);await nextTick();assert.equal(synthesis.utterances.length,1);assert.ok(states.some(event=>event.state==='cancelled'&&event.cardId==='card'));});
