import test from 'node:test';import assert from 'node:assert/strict';import {createListeningProgressStore} from '../src/features/listening/listening-progress.js';import {contentLoader} from '../src/content/repository/content-loader.js';import {renderSpeakingSection} from '../src/components/speaking-section.js';import {createRecordingSession} from '../src/features/speaking/recording-session.js';
const makeStorage=()=>{const data=new Map();return{getItem:key=>data.get(key)??null,setItem:(key,value)=>data.set(key,value)};};
test('word tracking starts at zero, increments once per action, caps at five, and persists',()=>{const storage=makeStorage();let store=createListeningProgressStore({storage});assert.deepEqual(store.getVocabularyState('u','w'),{unitId:'u',wordId:'w',uses:0,targetUses:5,learned:false,status:'not-started'});for(let n=1;n<=5;n++)assert.equal(store.recordVocabularyUse('u','w').uses,n);assert.equal(store.getVocabularyState('u','w').status,'mastered');assert.equal(store.recordVocabularyUse('u','w').changed,false);assert.equal(store.getVocabularyState('u','w').uses,5);store=createListeningProgressStore({storage});assert.equal(store.getVocabularyState('u','w').uses,5);});
test('word summary is data-derived and existing listen state shares the same storage',()=>{const store=createListeningProgressStore({storage:makeStorage()});const items=[{id:'a'},{id:'b'},{id:'c'}];store.recordCompletedListen('u');store.recordVocabularyUse('u','a');for(let i=0;i<5;i++)store.recordVocabularyUse('u','b');assert.deepEqual(store.getWordTrackingSummary('u',items),{mastered:1,total:3});assert.equal(store.get('u').listensCompleted,1);});
test('word progress subscriptions allow filters and UI to refresh immediately',()=>{const store=createListeningProgressStore({storage:makeStorage()}),events=[];store.subscribe(event=>events.push(event));store.recordVocabularyUse('u','a');assert.equal(store.getVocabularyState('u','a').status,'in-progress');store.recordVocabularyUse('u','a');assert.equal(events.at(-1).wordId,'a');assert.equal(events.at(-1).type,'vocabulary');});
test('real normalized prompts render dynamically for A2, B1, and B1+',async()=>{for(const bookId of ['a2-foundation','b1-core','b1-plus-bridge']){const unit=await contentLoader.getUnit(`${bookId}:unit:1`);assert.equal(unit.speakingPrompts.length,4);const html=renderSpeakingSection(unit.speakingPrompts);assert.match(html,new RegExp(`0\\/${unit.speakingPrompts.length}`));assert.ok(html.includes(unit.speakingPrompts[0].text));assert.match(html,/Recording/);}});
test('speaking completion is explicit, persists, and remains separate from word marks',()=>{const storage=makeStorage();let store=createListeningProgressStore({storage}),prompts=[{id:'p1'},{id:'p2'}];assert.deepEqual(store.getSpeakingSummary('u',prompts),{completed:0,total:2});store.setSpeakingCompleted('u','p1',true);assert.deepEqual(store.getSpeakingSummary('u',prompts),{completed:1,total:2});assert.equal(store.getVocabularyState('u','w').uses,0);store=createListeningProgressStore({storage});assert.equal(store.getSpeakingState('u','p1').completed,true);});
function fakeRecorderSetup(){const tracks=[{stopped:0,stop(){this.stopped++;}}];let instance;class Recorder{constructor(stream){this.stream=stream;this.state='inactive';this.mimeType='audio/webm';instance=this;}start(){this.state='recording';this.onstart?.();}stop(){this.state='inactive';this.ondataavailable?.({data:new Blob(['audio'])});this.onstop?.();}}const urls=new Map();let id=0;return{Recorder,get instance(){return instance;},tracks,URLApi:{createObjectURL(blob){const url=`blob:test-${++id}`;urls.set(url,blob);return url;},revokeObjectURL(url){urls.delete(url);}},urls,mediaDevices:{async getUserMedia(){return{getTracks:()=>tracks};}}};}
test('recording session requests mic, records, stops into playable object URL, and deletes it',async()=>{const f=fakeRecorderSetup(),events=[];const session=createRecordingSession({mediaDevices:f.mediaDevices,MediaRecorderType:f.Recorder,URLApi:f.URLApi,onState:event=>events.push(event)});await session.start();assert.equal(session.getState().status,'recording');const ready=await session.stop();assert.equal(ready.status,'ready');assert.ok(ready.url.startsWith('blob:'));assert.equal(f.urls.has(ready.url),true);assert.equal(f.tracks[0].stopped,1);await session.delete();assert.equal(session.getState().status,'deleted');assert.equal(f.urls.size,0);assert.ok(events.some(x=>x.status==='recording'));});
test('microphone denial and unsupported recording have graceful fallbacks',async()=>{const denied=createRecordingSession({mediaDevices:{getUserMedia:async()=>{const error=new Error('no');error.name='NotAllowedError';throw error;}},MediaRecorderType:class{}});assert.match((await denied.start()).message,/permission was denied/);const unsupported=createRecordingSession({mediaDevices:null,MediaRecorderType:null});assert.match((await unsupported.start()).message,/not supported/);});
